---
  # Install Docker

- name: Install Docker-CE on CentOS
  block:
    - name: Add Docker Stable repo for CentOS
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes
        state: present

    - name: Install the latest stable version of docker-ce on CentOS
      yum:
        name: docker-ce
        state: latest

  when: ansible_distribution == 'CentOS'

- name: Install Docker-CE on Fedora
  block:
    - name: Add Docker Stable repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        gpgkey: https://download.docker.com/linux/fedora/gpg
        gpgcheck: yes
        enabled: yes
        state: present

    - name: Install the latest stable version of docker-ce on Fedora
      dnf:
        name: docker-ce
        state: latest

  when: ansible_distribution == 'Fedora'

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add {{ docker_user }} user to docker group
  user:
    name: '{{ docker_user }}'
    groups: docker
    append: yes
  when: docker_user != "vagrant" AND docker_user != "root"

- name: Enable IPv6, journald, and overlay2
  template:
    src: templates/daemon_ipv6.json
    dest: /etc/docker/daemon.json
  notify: restart docker
  when: docker_enable_ipv6 == "true"
  # tags:
  #   - ipv6

- name: Enable journald, and overlay2
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker
  when: docker_enable_ipv6 != "true"

- name: Create volumes directory
  file:
    path: '{{ ansible_env.HOME }}/volumes'
    state: directory

- name: Download and install Docker Compose {{ docker_compose_ver }}
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    mode: 0755

- name: Initialize Docker Swarm Master
  command: "docker swarm init --advertise-addr {{ docker_swarm_master_ip }}"
  when: docker_swarm_state == "master"
  notify: restart docker

- name: Connect Worker Node to Docker Swarm Master Server
  command: "docker swarm join --token {{ docker_swarm_join_token }} {{ docker_swarm_master_ip }}:{{ docker_swarm_master_port }}"
  when: docker_swarm_state == "minion"
  notify: restart docker
